const fs = require("fs");
const path = require("path");
const { ethers } = require("ethers");
const { milestoneSizes } = require("./projectRisk");

// Load the compiled contract's ABI + bytecode, generated by Hardhat when you ran `npx hardhat compile`
const escrowArtifactPath = path.join(
  __dirname,
  "../../contracts/artifacts/contracts/Escrow.sol/Escrow.json",
);
const escrowArtifact = JSON.parse(fs.readFileSync(escrowArtifactPath, "utf8"));

const RISK_CATEGORY_TO_NUMBER = { Low: 0, Medium: 1, High: 2 };

const BUDGET_TO_ETH_RATE =
  require("../config/blockchainConfig").BUDGET_TO_ETH_RATE;

/**
 * Assembles everything the frontend needs to deploy an Escrow contract
 * for this project via the client's own MetaMask wallet.
 * Does NOT send any transaction itself -- purely prepares data.
 */
function getEscrowDeploymentParams(project) {
  if (!project.lastRiskAssessment || !project.lastRiskAssessment.computedAt) {
    throw new Error("Project has no risk assessment yet. Run /assess first.");
  }
  if (!project.client.walletAddress || !project.freelancer.walletAddress) {
    throw new Error(
      "Client and freelancer must both have wallet addresses set.",
    );
  }

  const { exposureLimit, milestoneCount, riskCategory } =
    project.lastRiskAssessment;

  const sizesInBudgetUnits = milestoneSizes(exposureLimit, milestoneCount);
  const sizesInEth = sizesInBudgetUnits.map(
    (amount) => amount * BUDGET_TO_ETH_RATE,
  );
  const sizesInWei = sizesInEth.map((eth) =>
    ethers.parseEther(eth.toFixed(18)),
  );

  const totalWei = sizesInWei.reduce((sum, w) => sum + w, 0n);

  return {
    abi: escrowArtifact.abi,
    bytecode: escrowArtifact.bytecode,
    constructorArgs: [
      project.client.walletAddress,
      project.freelancer.walletAddress,
      process.env.ORACLE_ADDRESS,
      RISK_CATEGORY_TO_NUMBER[riskCategory],
      project.requirementHash,
      sizesInWei.map((w) => w.toString()), // stringified for safe JSON transport
    ],
    totalValueWei: totalWei.toString(),
  };
}

module.exports = { getEscrowDeploymentParams };
